apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-config-secret
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  dataFrom:
    - extract:
        key: mks_api_config
