apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sts
  labels:
    app: postgres
spec:
  replicas: 1
  serviceName: postgres-headless-svc
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:18.4-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-config-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-config-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-config-secret
                  key: DB_NAME
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          app: postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
