// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
}

var _ Querier = (*Queries)(nil)
